//error: 'catch' without 'try' block
//because we used finally block so, error occurs

class Test7{
	public static void main(String[] args) {
		try{

		}
		finally{

		}
		catch (Exception e) {
			
		}
	}
}